---
- id: 'STRICT'
  absolute: true

- id: 'PERMISSIVE'
  absolute: false
  thresholds:
    "hate": 0.7
    "hate/threatening": 0.6
    "self-harm": 0.3
    "sexual": 0.7
    "sexual/minors": 0.2
    "violence": 0.7
    "violence/graphic": 0.4
