---
- id: 'RPG'
  model-name: 'chatgpt'
  name: 'Default dungeon master settings'
  max-tokens: 350
  chat-history-memory: 5
  temperature: 0.8
  frequency-penalty: 0.2
  presence-penalty: 0.2

- id: 'CHATBOT'
  name: 'Default chatbot settings'
  model-name: 'chatgpt'
  max-tokens: 100
  chat-history-memory: 5
  temperature: 0.8
  frequency-penalty: 0.2
  presence-penalty: 0.2
  stop-sequence:
    - "\n"