version: "3"
networks:
  ? dockerlan
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: malaquias
      MONGO_INITDB_ROOT_PASSWORD: malaquias
  mongo-express:
    container_name: mongo
    hostname: mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: malaquias
      ME_CONFIG_MONGODB_ADMINPASSWORD: malaquias
      ME_CONFIG_MONGODB_URL: mongodb://malaquias:malaquias@mongodb:27017/