version: "3"
networks:
  ? dockerlan
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: malaquias
      MONGO_INITDB_ROOT_PASSWORD: malaquias