version: "3"
networks:
  ? dockerlan
services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres:15-alpine
    networks:
      - dockerlan
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatrpg
      POSTGRES_PASSWORD: chatrpg
      POSTGRES_DB: chatrpg