app = "chatrpg"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"
processes = []

[env]
  POSTGRES_HOST = "chatrpg-db.internal:5432"
  POSTGRES_USER = "chatrpg"
  POSTGRES_DB = "chatrpg"
