app = "chatrpg"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "mad"
processes = []

[env]
  POSTGRES_DB = "chatrpg"
  POSTGRES_HOST = "chatrpg-db.internal:5432"
  POSTGRES_USER = "chatrpg"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = "8080"