config:
    bot:
        generation:
            default-max-tokens: 100
            default-temperature: 0.6
            default-presence-penalty: 0.2
            default-frequency-penalty: 0.2
            default-threshold: 1.0
    discord:
        api-token: ${DISCORD_BOT_API_TOKEN}
    openai:
        moderation-uri: /v1/moderations
        completions-uri: /v1/chat/completions
        chat-completions-uri: /v1/completions
        api-base-url: https://api.openai.com
        api-token: ${OPENAI_API_TOKEN}

spring:
    profiles.active: default
    main:
        banner-mode: "off"
    jpa.hibernate.ddl-auto: update
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

logging:
    level:
        root: INFO
        es.thalesalv: INFO
        org.hibernate: ERROR
        com.zaxxer.hikari: ERROR
        net.dv8tion.jda: ERROR
        org.springframework: ERROR
        ch.qos.logback: ERROR