config:
    discord:
        api-token: ${DISCORD_BOT_API_TOKEN}
    openai:
        api-token: ${OPENAI_API_TOKEN}

spring:
    jpa.hibernate.ddl-auto: update
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
