config:
    bot:
        generation:
            default-max-tokens: 100
            default-temperature: 0.6
            default-presence-penalty: 0.2
            default-frequency-penalty: 0.2
    discord:
        api-token: ${DISCORD_BOT_API_TOKEN}
    openai:
        api-token: ${OPENAI_API_TOKEN}

spring:
    main:
        banner-mode: off
    data:
        mongodb:
            database: ${MONGODB_DB}
            host: ${MONGODB_USER}
            username: ${MONGODB_USER}
            password: ${MONGODB_PASSWORD}

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        ch.qos.logback: OFF