config:
    bot:
        generation:
            default-max-tokens: 100
            default-temperature: 0.6
            default-presence-penalty: 0.2
            default-frequency-penalty: 0.2
    discord:
        api-token: ${DISCORD_BOT_API_TOKEN}
    openai:
        api-token: ${OPENAI_API_TOKEN}

spring:
    main:
        banner-mode: off
    data:
        mongodb:
            uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}/${MONGODB_DB}?authSource=admin&authMechanism=SCRAM-SHA-1
            database: ${MONGODB_DB}
            username: ${MONGODB_USER}
            password: ${MONGODB_PASSWORD}
            host: ${MONGODB_HOST}

logging:
    level:
        root: INFO
        org.mongodb: ERROR
        net.dv8tion.jda: ERROR
        org.springframework: ERROR
        ch.qos.logback: ERROR