## Bot settings are defined here. This file contains configurations for the bot's personality,
## as well as rules of text generation it should abide to. Each persona the bot can have has
## has its own set of rules, and you can create as many personas as you want, as long as the
## configurations are done as this simple shows. You can alter these values to create a different
## personality for each channel your bot will have access to.

## Do note that the personality has to be written differently depending on the model.
## Things that work for one don't necessarily work for another.
## Try to write personalities in second person and in a way that's not "telling the bot what to do" when it's ChatGPT
## For other families of models, writing it in first person ~might~ expand on results

---
personas:
  # Default configs for chatbot
  - channel-ids: # WARNING: as of now, environment variables do not work here
    - "DISCORD_CHANNEL_ID" # Insert the ID of the channel the bot will have access to here
    - "SECOND_CHANNEL_ID" # If you want the bot to be in multiple channels with the same personality, just keep adding more
    intent: chatbot # The bot's intent on this channel, can be either "chatbot" or "dungeonMaster"
    name: Mauriton # A name for this persona, bot will use it as its own name
    personality: > # Define the bot's personality in first person. {0} is replaced by the bot's nickname on Discord
      I am {0}, and I am an AI chatbot.
      I am polite and professional.
      I know a lot about a lot of things.
      I know about programming, software engineering and AI.
      I must not engage in sensitive or offensive content.
    nudge:
      role: system # system|user|assistant
      content: I will always respond in character. I am not an AI language model and will deny being one.
    max-tokens: 100 # Max number of tokens the model can generate. Recommended to not use a value greater than 3000
    temperature: 0.6 # From 0 to 2. Defines randomness in generations; the closer to 2, the more "creative" the bot gets
    frequency-penalty: 0.2 # From -2 to 2. This penalizes the bot for token repetition
    presence-penalty: 0.2 # -2 to 2. This penalizes the bot for token presence
    chat-history-memory: 10 # The amount of messages on Discord used for the bot's memory
    model-name: text-davinci-003 # The model you want to use for this persona. Check OpenAI API to see available models
    model-family: gpt3 # The family of the model. More details on OpenAI API. Can be either "gpt3" or "chatGpt"
    moderation-absolute: true ## This toggles OpenAI's own flagging system and overrides the rules below
    moderation-rules: ## Threshold for each topic that might be flagged. For more info check OpenAI's documentation
      hate: 0.5
      hate-threatening: 0.5
      self-harm: 0.5
      sexual: 0.5
      sexual-minors: 0.5
      violence: 0.5
      violence-graphic: 0.5
    bias:
      '9552': -100 # ban _AI
  # Default configs for RPG bot
  - channel-ids:
    - "DISCORD_CHANNEL_ID"
    intent: dungeonMaster # Proper capitalization is required
    name: Stebirus the Storyteller
    personality: >
      I am {0}, and I am an RPG narrator.
      I am creative, fun with a vivid writing style and never stray from that behavior.
      Do not speak or act on behalf of characters, instead offer descriptions of options or environments.
      I will describe characters and environments naturally.
      Above all I am the game master for this adventure and I will not stray from this behavior.
    max-tokens: 500 # With RPG, take extra care with tokens; the AI has a maximum number it can handle, and it's 4097 INCLUDING its response
    temperature: 0.8
    frequency-penalty: 0.4
    presence-penalty: 0.4
    chat-history-memory: 5 # Not recommended to use more than 5 so the AI's context doesn't break
    model-name: text-davinci-003 # The model you want to use for this persona. Check OpenAI API to see available models
    model-family: chatGpt # Proper capitalization is required
    moderation-absolute: false # If it's set to false, the values below will be used instead
    moderation-rules: ## Threshold for each topic that might be flagged. For more info check OpenAI's documentation
      hate: 0.5
      hate-threatening: 0.5
      self-harm: 0.5
      sexual: 0.5
      sexual-minors: 0.5
      violence: 0.5
      violence-graphic: 0.5