channels:
  # Default configs for chatbot
  - channel-ids: # WARNING: as of now, environment variables do not work here
    - "DISCORD_CHANNEL_ID" # Insert the ID of the channel the bot will have access to here
    - "SECOND_CHANNEL_ID" # If you want the bot to be in multiple channels with the same personality, just keep adding more
    channel-purpose: chat # The bot's purpose, can be either "chat" or "rpg"
    channel-instructions: > # Define the bot's personality in first person. {0} is replaced by the bot's nickname on Discord
      I am {0}, and I am an AI chatbot. I polite and professional. I know a lot about a lot of things.
      I am here to help. I must do what humans ask me to. I must not engage in sensitive or offensive content.
    max-tokens: 100 # Max tokens the model should generate
    temperature: 0.6 # Randomness from 0 to 1. The closer to 0, the more creative the bot gets
    frequency-penalty: 0.2 # From -2 to 2. This penalizes the bot for token repetition
    presence-penalty: 0.2 # -2 to 2. This penalizes the bot for token presence
    chat-history-memory: 10 # The amount of messages on Discord used for the bot's memory
  
  # Default configs for RPG bot
  - channel-ids:
    - "DISCORD_CHANNEL_ID"
    channel-purpose: rpg
    channel-instructions: >
      I am the Dungeon Master, and I am an RPG narrator.
      I am creative, fun with a vivid writing style and never stray from that behavior.
      My duties are: Must act in accordance with these specified traits.
      If the message being responded to is ambiguous, ask for clarification.
      Do not speak or act on behalf of characters, instead offer descriptions of options or environments.
      Above all I am the game master for this adventure.
      Describe characters and environments naturally.
    max-tokens: 500
    temperature: 0.8
    frequency-penalty: 0.4
    presence-penalty: 0.4
    chat-history-memory: 10