name: Java CI
on: [push]
jobs:
  ChatRPG:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build with Maven
        run: git pull && mvn package -DskipTests
      - name: Push formatted code
        uses: actions-js/push@master
        with:
          branch: master
          message: "Automated commit: fix code style according to format"
          author_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit tests
        if: github.ref != 'refs/heads/master'
        run: mvn test
      - name: Code coverage
        if: github.ref == 'refs/heads/master'
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageCommand: mvn test
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
      - name: Install flyctl
        if: github.ref == 'refs/heads/master'
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        if: github.ref == 'refs/heads/master'
        run: flyctl deploy -a chatrpg
        env:
          FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}