name: Java CI
on: [push]
jobs:
  ChatRPG-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Create Persona
        if: github.ref == 'refs/heads/master'
        run: wget ${{secrets.PERSONA_FILE}} -O ${{github.workspace}}/src/main/resources/bot-config.yaml
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Unit tests
        if: github.ref != 'refs/heads/master'
        run: mvn test
      - name: Code coverage
        if: github.ref == 'refs/heads/master'
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageCommand: mvn test
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
  ChatRPG-Deploy:
    if: github.ref == 'refs/heads/master'
    needs: ChatRPG-Build
    runs-on: ubuntu-latest
    steps:
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy -a chatrpg
        env:
          FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
      - uses: geekyeggo/delete-artifact@v2
        with:
            name: ChatRPG artifacts