name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Unit tests
        run: mvn test
      - name: Code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref == 'refs/heads/master'
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageCommand: mvn test
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
      - name: Container registry
        uses: docker/login-action@v1
        with:
          registry: quay.io/thaalesalves
          username: ${{ secrets.QUAY_LOGIN }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Install pack CLI
        uses: buildpacks/github-actions/setup-pack@v4.8.1
      - name: Build image
        run: |
          pack build ghcr.io/jonashackt/spring-boot-flyio:latest \
              --builder paketobuildpacks/builder:tiny \
              --buildpack paketo-buildpacks/java-native-image@5.12.0 \
              --path . \
              --env "BP_JVM_VERSION=19" \
              --env "BP_NATIVE_IMAGE=true" \
              --cache-image ghcr.io/jonashackt/spring-boot-flyio-paketo-cache-image:latest \
              --publish
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy our Spring Boot app to fly.io
        run: flyctl deploy --image ghcr.io/jonashackt/spring-boot-flyio:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
