name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Unit tests
        run: mvn test
      - name: Code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref == 'refs/heads/master'
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageCommand: mvn test
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
      - name: Create image
        uses: redhat-actions/push-to-registry@v2.7
        with:
          registry: quay.io/thaalesalves
          image: chatrpg
          username: ${{ secrets.QUAY_LOGIN }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy our Spring Boot app to fly.io
        run: flyctl deploy --image quay.io/thaalesalves/chatrpg:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
